/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateChangeCountryView.java
 *
 * Created on 28-okt-2013, 14:05:21
 */
package View;

import Model.Country;
import javax.swing.JOptionPane;

/**
 *
 * @author Kelly
 */
public class CreateChangeCountryView extends javax.swing.JInternalFrame {
    private Country country = null;
    
    /** Creates new form CreateChangeCountryView */
    public CreateChangeCountryView(Country c) {
       initComponents();
        country = c;

        if (c != null) {
            FillFields();
        }
    }
    
    private void FillFields() {
        landcodeTextField.setText("" + country.getLandcode());
        countrynameTextField.setText("" + country.getCountry());
        regionTextField.setText("" + country.getRegion());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        landcodeTextField = new javax.swing.JTextField();
        countrynameTextField = new javax.swing.JTextField();
        regionTextField = new javax.swing.JTextField();
        countrySaveBT = new javax.swing.JButton();
        countryCancelBT = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        landcodeTextField1 = new javax.swing.JTextField();
        countrynameTextField1 = new javax.swing.JTextField();
        regionTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        countrySaveBT1 = new javax.swing.JButton();
        countryCancelBT1 = new javax.swing.JButton();
        lblError1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setRequestFocusEnabled(false);

        landcodeTextField.setName("landcodeTextField"); // NOI18N

        countrynameTextField.setName("countrynameTextField"); // NOI18N

        regionTextField.setName("regionTextField"); // NOI18N
        regionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionTextFieldActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flyaway.FlyAWayApp.class).getContext().getResourceMap(CreateChangeCountryView.class);
        countrySaveBT.setText(resourceMap.getString("countrySaveBT.text")); // NOI18N
        countrySaveBT.setName("countrySaveBT"); // NOI18N
        countrySaveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySaveBTActionPerformed(evt);
            }
        });

        countryCancelBT.setText(resourceMap.getString("countryCancelBT.text")); // NOI18N
        countryCancelBT.setName("countryCancelBT"); // NOI18N
        countryCancelBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryCancelBTActionPerformed(evt);
            }
        });

        lblError.setName("lblError"); // NOI18N

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setRequestFocusEnabled(false);

        landcodeTextField1.setName("landcodeTextField1"); // NOI18N

        countrynameTextField1.setName("countrynameTextField1"); // NOI18N

        regionTextField1.setName("regionTextField1"); // NOI18N
        regionTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setName("jLabel6"); // NOI18N

        countrySaveBT1.setName("countrySaveBT1"); // NOI18N
        countrySaveBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countrySaveBT1ActionPerformed(evt);
            }
        });

        countryCancelBT1.setName("countryCancelBT1"); // NOI18N
        countryCancelBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryCancelBT1ActionPerformed(evt);
            }
        });

        lblError1.setName("lblError1"); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(landcodeTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(regionTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(countrynameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(countrySaveBT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(countryCancelBT1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(lblError1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landcodeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(countrynameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countrySaveBT1)
                    .addComponent(countryCancelBT1))
                .addGap(34, 34, 34)
                .addComponent(lblError1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(countrySaveBT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(countryCancelBT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regionTextField)
                            .addComponent(countrynameTextField)
                            .addComponent(landcodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 214, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 215, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countrynameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countrySaveBT, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(countryCancelBT, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 146, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 147, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionTextFieldActionPerformed

    private void countrySaveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySaveBTActionPerformed
       String landcode = landcodeTextField.getText();
       Integer region = -1;
       String countryname = null;
       boolean dbResult = false;
        lblError.setText("");
        String ErrorMessage = "";
        if (landcode.isEmpty()) {
            ErrorMessage += "No landcode entered \n";
        }

        if (countrynameTextField.getText().isEmpty()) {
            ErrorMessage += "no Country name entered \n";
            
        }else{
            countryname = countrynameTextField.getText();
        }
        
         if(regionTextField.getText().isEmpty()){
                ErrorMessage += "No Region entered \n";
         }else{
                try {
                     region = Integer.parseInt(regionTextField.getText());
                }catch (NumberFormatException nfe) {
                    ErrorMessage += "Region isn't a number \n";
                }
         }
        

        if (ErrorMessage.isEmpty()) {
            if (country == null) {
                country = new Country();
                country.setLandcode(landcode);
                country.setCountry(countryname);
                country.setRegion(region);
                dbResult = Controller.Controller.Instance().save(country);
            } else {
                country.setLandcode(landcode);
                country.setCountry(countryname);
                country.setRegion(region);
                dbResult = Controller.Controller.Instance().update(country);
            }
            
            if (dbResult) {
                JOptionPane.showMessageDialog(this, "Country saved");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error while saving country!");
            }
        }
        lblError.setText(ErrorMessage);
    }//GEN-LAST:event_countrySaveBTActionPerformed

    private void countryCancelBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryCancelBTActionPerformed
         this.dispose();
    }//GEN-LAST:event_countryCancelBTActionPerformed

    private void regionTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionTextField1ActionPerformed

    private void countrySaveBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countrySaveBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countrySaveBT1ActionPerformed

    private void countryCancelBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryCancelBT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryCancelBT1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countryCancelBT;
    private javax.swing.JButton countryCancelBT1;
    private javax.swing.JButton countrySaveBT;
    private javax.swing.JButton countrySaveBT1;
    private javax.swing.JTextField countrynameTextField;
    private javax.swing.JTextField countrynameTextField1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField landcodeTextField;
    private javax.swing.JTextField landcodeTextField1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblError1;
    private javax.swing.JTextField regionTextField;
    private javax.swing.JTextField regionTextField1;
    // End of variables declaration//GEN-END:variables
}
