/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CreateChangeAirmarshall.java
 *
 * Created on 29-okt-2013, 13:06:39
 */
package View;

import Model.Airport;
import java.awt.Color;
import javax.swing.BorderFactory;
import Controller.Controller;
import Model.Airmarshall;
import Model.PersonalType;
import Model.Rank;
import javax.swing.JOptionPane;
import javax.swing.ToolTipManager;

/**
 *
 * @author Kelly
 */
public class CreateChangeAirmarshallView extends javax.swing.JInternalFrame {
        Airmarshall marshall = null;
        Airport airport = null;
        
    /** Creates new form CreateChangeAirmarshall */
    public CreateChangeAirmarshallView(Airmarshall am) {
        initComponents();

        
        marshall = am;
        if (am != null) {
            Fill(am);
        
        }
   }
            


 private void Fill(Airmarshall air) {
        txtFieldID.setText("" + air.getId());
        txtName.setText(air.getName());
        txtUsername.setText(air.getUsername());
        txtWeaponNr.setText(air.getWeaponNr());
        txPersonellNr.setText("" + air.getPersonnelNr());
        txtNationality.setText(air.getNationality());
  
        lblPassword.setText("Change password");
        
        if(air.getPrimaryAirport() != null){
        airport = air.getPrimaryAirport();
        txtAirport.setText(air.getPrimaryAirport().toString());
        
        }
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listSearchResults = new javax.swing.JList();
        txtUsername = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtAirport = new javax.swing.JTextField();
        txtWeaponNr = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtFieldID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txPersonellNr = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        lblError = new javax.swing.JLabel();
        txtNationality = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        listSearchResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listSearchResults.setEnabled(false);
        listSearchResults.setName("listSearchResults"); // NOI18N
        listSearchResults.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listSearchResultsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listSearchResults);

        txtUsername.setName("txtUsername"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(flyaway.FlyAWayApp.class).getContext().getResourceMap(CreateChangeAirmarshallView.class);
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        lblPassword.setText(resourceMap.getString("lblPassword.text")); // NOI18N
        lblPassword.setName("lblPassword"); // NOI18N

        txtAirport.setName("txtAirport"); // NOI18N
        txtAirport.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAirportFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAirportFocusLost(evt);
            }
        });

        txtWeaponNr.setName("txtWeaponNr"); // NOI18N

        txtPassword.setName("txtPassword"); // NOI18N

        txtFieldID.setEditable(false);
        txtFieldID.setToolTipText(resourceMap.getString("txtFieldID.toolTipText")); // NOI18N
        txtFieldID.setName("txtFieldID"); // NOI18N
        txtFieldID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtFieldIDMouseEntered(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        lblPassword1.setText(resourceMap.getString("lblPassword1.text")); // NOI18N
        lblPassword1.setName("lblPassword1"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        txPersonellNr.setName("txPersonellNr"); // NOI18N

        btnSave.setText(resourceMap.getString("btnSave.text")); // NOI18N
        btnSave.setName("btnSave"); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText(resourceMap.getString("btnCancel.text")); // NOI18N
        btnCancel.setName("btnCancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtName.setName("txtName"); // NOI18N

        lblError.setName("lblError"); // NOI18N

        txtNationality.setName("txtNationality"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblError, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPassword1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNationality, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtWeaponNr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txPersonellNr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtAirport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtFieldID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                .addGap(78, 78, 78)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txPersonellNr, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWeaponNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword1))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(32, 32, 32)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listSearchResultsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listSearchResultsValueChanged
        Airport tmpAirport = (Airport) listSearchResults.getSelectedValue();
        
        if (tmpAirport != null) {
            airport = tmpAirport;
            txtAirport.setText(airport.toString());
            
        }
}//GEN-LAST:event_listSearchResultsValueChanged

    private void txtAirportFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAirportFocusGained
        txtAirport.setBorder(BorderFactory.createLineBorder(Color.orange));
        listSearchResults.setEnabled(true);
        listSearchResults.setListData(Controller.Instance().getAirports().toArray());
}//GEN-LAST:event_txtAirportFocusGained

    private void txtAirportFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAirportFocusLost
        txtAirport.setBorder(BorderFactory.createLineBorder(Color.lightGray));
        listSearchResults.setEnabled(false);
}//GEN-LAST:event_txtAirportFocusLost

    private void txtFieldIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldIDMouseEntered
        txtFieldID.setToolTipText("The ID will be automatically generated");
        ToolTipManager.sharedInstance().setInitialDelay(1);
}//GEN-LAST:event_txtFieldIDMouseEntered

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = txtName.getText();
        String password = txtPassword.getText();
        int staffId = -1;
        int personellNr = -1;
        PersonalType st = PersonalType.Airmarshall;
        String username = txtUsername.getText();
        String weaponNr = txtWeaponNr.getText();
        personellNr = Integer.parseInt(txPersonellNr.getText());
        String nationality = txtNationality.getText();
        

        String errorMessage = "";
        name.trim();
        password.trim();
        if (name.isEmpty()) {
            errorMessage += "*  Please enter a name first <br>";
        }
        if(username.isEmpty()){
            errorMessage += "*  Please enter a username <br>";
        }
        if((marshall == null) && (password.isEmpty())){
            errorMessage += "*  Please enter a password <br>";
        }
        if(weaponNr.isEmpty()){
            errorMessage += "* Please enter a weaponnumber <br>";
        }
        
        if(personellNr <0){
            errorMessage += "* Please enter a personellnumber <br>";
        }
        
        if(nationality.isEmpty()){
            errorMessage += "* Please enter a nationality <br>";
        }
        

        if (errorMessage.isEmpty()) {
            if (marshall == null) {
                marshall = new Airmarshall();
                marshall.setName(name);
                marshall.setUsername(username);
                marshall.setPrimaryAirport(airport);
                marshall.setType(st);
                marshall.setPassword(password, true);
                marshall.setNationality(nationality);
                marshall.setPersonnelNr(personellNr);
                marshall.setWeaponNr(weaponNr);
                marshall.setRank(Rank.STAFF);
                

                if (Controller.Instance().save(marshall)) {
                    JOptionPane.showMessageDialog(this, "Marshall " + marshall.getName() + " Saved");
                    this.dispose();
                }
            } else {
                marshall.setName(name);
                marshall.setUsername(username);
                
                if(txtAirport.getText().isEmpty()){
                marshall.setPrimaryAirport(null);
                }else{
                marshall.setPrimaryAirport(airport);                        
                }
                marshall.setType(st);
                marshall.setPassword(password, true);
                marshall.setNationality(nationality);
                marshall.setPersonnelNr(personellNr);
                marshall.setWeaponNr(weaponNr);
                marshall.setRank(Rank.STAFF);

                if (Controller.Instance().update(marshall)) {
                    JOptionPane.showMessageDialog(this, "Marshall " + marshall.getName() + " Saved");
                    this.dispose();
                }
            }
            this.dispose();
        }
        lblError.setText("<html> " + errorMessage + " </html>");
                                        
}//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
}//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JList listSearchResults;
    private javax.swing.JTextField txPersonellNr;
    private javax.swing.JTextField txtAirport;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtWeaponNr;
    // End of variables declaration//GEN-END:variables
}
